console.log('hello world.');
var h1 = document.querySelector('h1');
console.log(h1);
console.dir(h1);
var explanation = document.querySelector('#explanation');
console.log(explanation);
console.dir(explanation);
var classSelect = document.querySelector('.hint');
console.log(classSelect);
console.dir(classSelect);
console.log(document.querySelectorAll('p'));
console.log(document.querySelectorAll('.example-link'));
